# Generated by Django 6.0 on 2025-12-27 13:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('provider', 'day_of_week')},
        ),
    ]
